org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.17.2
loom_version=1.10.5
fabric_api_version=0.116.10+1.21.1
fabric_kotlin_version=1.13.10+kotlin.2.3.20
cobblemon_project_id=MdwFAVRL
cobblemon_version_id=kF7CvxTo

mod_version=3.7.0-beta.1
maven_group=com.cobbleclub
archives_base_name=cobbleclub
