name: Build CobbleClub 3.9.23 Latest

on:
  push:
    branches:
      - CobbleClub-V3.9.23-Claims-Kits-Warps
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - run: chmod +x gradlew
      - run: ./gradlew clean build --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: CobbleClub-3.9.23-latest
          path: build/libs/*.jar
          if-no-files-found: error
